---
output: html_fragment
---

**About the ‘Imi Pono Hawaiʻi Wellbeing Survey:**

The ‘Imi Pono Hawaiʻi Wellbeing Survey is a statewide survey examining wellbeing among Native Hawaiians and Hawai’i residents from holistic and strengths-based perspectives. This survey is a partnership between Kamehameha Schools, Lili‘uokalani Trust, and the Office of Hawaiian Affairs and contracted with Marzano Research.

Data were collected from November 2020 through February 2021. A total of 1,458 participants took this survey, about half of whom reported being Native Hawaiian. The confidence intervals for the State and Honolulu County—including breakouts for Native Hawaiians within these areas—are five percent or less. Confidence intervals for other counties are higher; therefore findings for these counties should not be generalized beyond the survey sample. Data were collected via email, phone, postcard, and social media outlets. Given this, it is likely that the sample of survey respondents are more financially affluent than the general Native Hawaiian and Hawai’i population

**Recommended citation:**

Kamehameha Schools’ Strategy & Transformation Group, Liliʻuokalani Trust, and Office of Hawaiian Affairs. *‘Imi Pono Hawaiʻi Wellbeing Survey 2021: COVID-19 Impacts.* Honolulu: Author, May 2021. 

Please see https://www.ksbe.edu/research/imi_pono_hawaii_wellbeing_survey/ for more information on the survey and to access published briefs.

**About the dashboard:**

This interactive dashboard provides results for the 2021 survey administration. Results can be explored for each survey question and further broken out by respondent demographics.
